before_install:
- sudo apt-get install -y python-pip build-essential python-dev ffmpeg libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev libsdl1.2-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev

language: python
python: "2.7"
install: "pip install -r requirements.txt"
script: nose2
